# Tox (https://tox.testrun.org/) is a tool for running tests
# in multiple virtualenvs. This configuration file will run the
# test suite on all supported python versions. To use it, "pip install tox"
# and then run "tox" from this directory.

[tox]
envlist=3.{8,9,10,11,12,13,14}{,-tf}{,-keras}, perf, check
isolated_build=True

[gh]
python=
    3.8 = 3.8
    3.9 = 3.9
    3.10 = 3.10
    3.11 = 3.11
    3.12 = 3.12
    3.13 = 3.13-tf,3.13-tf-keras
    3.14 = 3.14

[core]
deps=
    pytest
    pytest-cov
    pytest-timeout
    pytest-asyncio
    ipywidgets
    git+https://github.com/casperdcl/nbval
    coverage
    coveralls
    codecov
commands=
    - coveralls
    codecov -X pycov -e TOXENV
    - codacy report -l Python -r coverage.xml --partial

[testenv]
passenv=TOXENV,CI,GITHUB_*,CODECOV_*,COVERALLS_*,CODACY_*,HOME
deps=
    {[core]deps}
    cython
    dask[delayed]
    matplotlib
    numpy
    pandas
    rich
    tf: tensorflow!=2.5.0
    keras: keras
commands=
    pytest --cov=tqdm --cov-report= -k "not perf"
    pytest --cov=tqdm --cov-report=xml --cov-report=term --cov-append -W=ignore tests_notebook.ipynb --nbval --nbval-current-env --nbval-sanitize-with=.meta/nbval.ini
    {[core]commands}
allowlist_externals=codacy

# no cython/numpy/pandas
[testenv:pypy3]
deps={[core]deps}

[testenv:perf]
deps=
    pytest
    pytest-timeout
    pytest-asyncio
commands=pytest -k perf

[testenv:check]
deps=
    build
    twine
    py-make>=0.1.0
commands=
    {envpython} -m build
    {envpython} -m twine check dist/*
    {envpython} -m pymake -h
